spring.application.name=gpfcalculator

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GPFDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Akash@12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# ==========================
# EMAIL CONFIGURATION
# ==========================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=work.station.caab@gmail.com
spring.mail.password=kfvu esbp pazh vbqm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

server.port=8083